# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CleanArchitechtureDrill' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CleanArchitechtureDrill
  pod 'FLEX', :configurations => ['Debug']

end
